apiVersion: v1
kind: Service
metadata:
  name: go-api-svc
spec:
  type: NodePort
  selector:
    app: go-api
  ports:
    - name: http
      port: 8050
      targetPort: 8050
      nodePort: 30090 
      protocol: TCP